name: crew
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  moor:
  sqlite3_flutter_libs:
  path_provider:
  path:
  provider: ^5.0.0
  uuid: 3.0.4
  collapsible: ^1.0.0
  flutter_staggered_grid_view:
  intl: ^0.17.0
  confetti: 0.6.0-nullsafety

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  source_gen:
  moor_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/images/space.jpg
    - assets/images/deepSea.jpg
    - assets/images/mission-marker.png
    - assets/images/mission-marker-gold.png
    - assets/images/fail-marker.png
    - assets/images/pass-marker.png
    - assets/json/missions.json
